class AppSchemaSql {
  const AppSchemaSql._();

  static const int schemaVersion = 3;

  static const List<String> tableNames = <String>[
    'companies',
    'staff_users',
    'roles',
    'permissions',
    'project_staff_assignments',
    'bidder_profiles',
    'tenders',
    'tender_expenses',
    'tender_documents',
    'projects',
    'project_agreement_deductions',
    'project_milestones',
    'work_days',
    'suppliers',
    'material_purchases',
    'material_purchase_items',
    'supplier_payments',
    'fuel_types',
    'fuel_entries',
    'laborers',
    'labor_work_entries',
    'labor_payments',
    'labor_advances',
    'machines',
    'machine_usage_entries',
    'machine_rental_payments',
    'machine_repair_entries',
    'project_estimates',
    'project_estimate_items',
    'project_bills',
    'project_bill_receipts',
    'gst_entries',
    'project_expenses',
    'sync_queue',
    'sync_deltas_applied',
    'sync_conflicts',
    'device_registry',
    'staff_access_cache'
  ];

  static const List<String> pragmas = <String>[
    'PRAGMA foreign_keys = ON;',
    'PRAGMA journal_mode = WAL;',
    'PRAGMA synchronous = NORMAL;',
  ];

  static const List<String> createTables = <String>[
    '''
    CREATE TABLE IF NOT EXISTS companies (
      id TEXT PRIMARY KEY,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      name TEXT NOT NULL,
      gst_number TEXT,
      pan_number TEXT,
      address TEXT,
      phone TEXT,
      email TEXT,
      logo_path TEXT,
      financial_year_start INTEGER,
      financial_year_end INTEGER
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS staff_users (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      firebase_uid TEXT,
      name TEXT NOT NULL,
      phone TEXT,
      email TEXT,
      role_id TEXT,
      status TEXT NOT NULL DEFAULT 'invited',
      last_login_at INTEGER,
      last_sync_at INTEGER
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS roles (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      name TEXT NOT NULL,
      description TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS permissions (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      role_id TEXT NOT NULL,
      permission_key TEXT NOT NULL,
      is_allowed INTEGER NOT NULL DEFAULT 0
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS project_staff_assignments (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      project_id TEXT NOT NULL,
      staff_id TEXT NOT NULL,
      role TEXT,
      can_view INTEGER NOT NULL DEFAULT 1,
      can_edit INTEGER NOT NULL DEFAULT 0,
      can_approve INTEGER NOT NULL DEFAULT 0
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS bidder_profiles (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      profile_name TEXT NOT NULL,
      portal_name TEXT,
      username TEXT,
      registered_mobile TEXT,
      registered_email TEXT,
      notes TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS tenders (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      bidder_profile_id TEXT,
      tender_number TEXT,
      tender_title TEXT NOT NULL,
      department_name TEXT,
      client_name TEXT,
      location TEXT,
      tender_type TEXT,
      tender_category TEXT,
      application_date INTEGER,
      submission_date INTEGER,
      opening_date INTEGER,
      result_date INTEGER,
      estimated_tender_value_paise INTEGER NOT NULL DEFAULT 0,
      quoted_tender_price_paise INTEGER NOT NULL DEFAULT 0,
      emd_amount_paise INTEGER NOT NULL DEFAULT 0,
      tender_fee_paise INTEGER NOT NULL DEFAULT 0,
      document_fee_paise INTEGER NOT NULL DEFAULT 0,
      processing_cost_paise INTEGER NOT NULL DEFAULT 0,
      other_application_cost_paise INTEGER NOT NULL DEFAULT 0,
      status TEXT NOT NULL DEFAULT 'draft',
      selected_date INTEGER,
      rejection_reason TEXT,
      notes TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS tender_expenses (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      tender_id TEXT NOT NULL,
      expense_date INTEGER NOT NULL,
      expense_type TEXT NOT NULL,
      description TEXT,
      amount_paise INTEGER NOT NULL DEFAULT 0,
      paid_to TEXT,
      payment_mode TEXT,
      receipt_path TEXT,
      notes TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS tender_documents (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      tender_id TEXT NOT NULL,
      document_type TEXT,
      file_name TEXT NOT NULL,
      local_path TEXT,
      firebase_storage_path TEXT,
      content_hash TEXT,
      uploaded_at INTEGER
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS projects (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      tender_id TEXT,
      project_code TEXT,
      project_name TEXT NOT NULL,
      client_name TEXT,
      department_name TEXT,
      site_location TEXT,
      start_date INTEGER,
      expected_end_date INTEGER,
      actual_end_date INTEGER,
      project_status TEXT NOT NULL DEFAULT 'planned',
      tender_quoted_price_paise INTEGER NOT NULL DEFAULT 0,
      approved_tender_amount_paise INTEGER NOT NULL DEFAULT 0,
      agreement_gross_value_paise INTEGER NOT NULL DEFAULT 0,
      agreement_final_value_paise INTEGER NOT NULL DEFAULT 0,
      gst_rate_basis_points INTEGER NOT NULL DEFAULT 0,
      retention_percent_basis_points INTEGER NOT NULL DEFAULT 0,
      security_deposit_amount_paise INTEGER NOT NULL DEFAULT 0,
      performance_guarantee_amount_paise INTEGER NOT NULL DEFAULT 0,
      advance_received_paise INTEGER NOT NULL DEFAULT 0,
      notes TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS project_agreement_deductions (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      project_id TEXT NOT NULL,
      deduction_date INTEGER NOT NULL,
      deduction_type TEXT NOT NULL,
      description TEXT,
      amount_paise INTEGER NOT NULL DEFAULT 0,
      is_recoverable INTEGER NOT NULL DEFAULT 0,
      notes TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS project_milestones (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      project_id TEXT NOT NULL,
      title TEXT NOT NULL,
      description TEXT,
      planned_date INTEGER,
      completed_date INTEGER,
      status TEXT,
      payment_linked_amount_paise INTEGER NOT NULL DEFAULT 0
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS work_days (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      project_id TEXT NOT NULL,
      work_date INTEGER NOT NULL,
      site_name TEXT,
      weather TEXT,
      notes TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS suppliers (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      supplier_name TEXT NOT NULL,
      contact_person TEXT,
      phone TEXT,
      gst_number TEXT,
      address TEXT,
      opening_balance_paise INTEGER NOT NULL DEFAULT 0,
      notes TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS material_purchases (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      project_id TEXT NOT NULL,
      supplier_id TEXT,
      purchase_date INTEGER NOT NULL,
      bill_number TEXT,
      invoice_number TEXT,
      vehicle_number TEXT,
      delivery_location TEXT,
      total_before_tax_paise INTEGER NOT NULL DEFAULT 0,
      gst_amount_paise INTEGER NOT NULL DEFAULT 0,
      total_amount_paise INTEGER NOT NULL DEFAULT 0,
      paid_amount_paise INTEGER NOT NULL DEFAULT 0,
      pending_amount_paise INTEGER NOT NULL DEFAULT 0,
      payment_status TEXT NOT NULL DEFAULT 'unpaid',
      notes TEXT,
      bill_image_path TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS material_purchase_items (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      purchase_id TEXT NOT NULL,
      project_id TEXT NOT NULL,
      material_name TEXT NOT NULL,
      details TEXT,
      unit TEXT,
      quantity_decimal TEXT NOT NULL DEFAULT '0',
      rate_paise INTEGER NOT NULL DEFAULT 0,
      amount_paise INTEGER NOT NULL DEFAULT 0,
      gst_rate_basis_points INTEGER NOT NULL DEFAULT 0,
      gst_amount_paise INTEGER NOT NULL DEFAULT 0,
      total_amount_paise INTEGER NOT NULL DEFAULT 0
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS supplier_payments (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      supplier_id TEXT NOT NULL,
      project_id TEXT,
      purchase_id TEXT,
      payment_date INTEGER NOT NULL,
      amount_paise INTEGER NOT NULL DEFAULT 0,
      payment_mode TEXT,
      reference_number TEXT,
      notes TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS fuel_types (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      name TEXT NOT NULL,
      unit TEXT NOT NULL,
      default_rate_paise INTEGER NOT NULL DEFAULT 0
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS fuel_entries (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      project_id TEXT NOT NULL,
      fuel_date INTEGER NOT NULL,
      fuel_type_id TEXT NOT NULL,
      quantity_decimal TEXT NOT NULL DEFAULT '0',
      rate_paise INTEGER NOT NULL DEFAULT 0,
      total_amount_paise INTEGER NOT NULL DEFAULT 0,
      used_for_type TEXT NOT NULL,
      machine_id TEXT,
      labor_id TEXT,
      supplier_id TEXT,
      vehicle_name TEXT,
      description TEXT,
      paid_amount_paise INTEGER NOT NULL DEFAULT 0,
      pending_amount_paise INTEGER NOT NULL DEFAULT 0,
      payment_status TEXT NOT NULL DEFAULT 'unpaid',
      notes TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS laborers (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      name TEXT NOT NULL,
      phone TEXT,
      address TEXT,
      labor_type TEXT,
      default_work_type TEXT,
      default_rate_paise INTEGER NOT NULL DEFAULT 0,
      notes TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS labor_work_entries (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      project_id TEXT NOT NULL,
      labor_id TEXT NOT NULL,
      work_date INTEGER NOT NULL,
      work_description TEXT,
      work_type TEXT NOT NULL,
      quantity_decimal TEXT NOT NULL DEFAULT '0',
      unit TEXT,
      rate_paise INTEGER NOT NULL DEFAULT 0,
      total_amount_paise INTEGER NOT NULL DEFAULT 0,
      paid_amount_paise INTEGER NOT NULL DEFAULT 0,
      pending_amount_paise INTEGER NOT NULL DEFAULT 0,
      payment_status TEXT NOT NULL DEFAULT 'unpaid',
      notes TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS labor_payments (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      labor_id TEXT NOT NULL,
      project_id TEXT,
      payment_date INTEGER NOT NULL,
      amount_paise INTEGER NOT NULL DEFAULT 0,
      payment_mode TEXT,
      reference_number TEXT,
      notes TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS labor_advances (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      labor_id TEXT NOT NULL,
      project_id TEXT,
      advance_date INTEGER NOT NULL,
      amount_paise INTEGER NOT NULL DEFAULT 0,
      recovered_amount_paise INTEGER NOT NULL DEFAULT 0,
      balance_amount_paise INTEGER NOT NULL DEFAULT 0,
      notes TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS machines (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      machine_name TEXT NOT NULL,
      machine_type TEXT,
      ownership_type TEXT NOT NULL,
      owner_name TEXT,
      owner_phone TEXT,
      registration_number TEXT,
      default_charge_type TEXT,
      default_charge_rate_paise INTEGER NOT NULL DEFAULT 0,
      notes TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS machine_usage_entries (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      project_id TEXT NOT NULL,
      machine_id TEXT NOT NULL,
      usage_date INTEGER NOT NULL,
      work_description TEXT,
      charge_type TEXT NOT NULL,
      hours_used_decimal TEXT,
      days_used_decimal TEXT,
      quantity_decimal TEXT,
      rate_paise INTEGER NOT NULL DEFAULT 0,
      total_amount_paise INTEGER NOT NULL DEFAULT 0,
      paid_amount_paise INTEGER NOT NULL DEFAULT 0,
      pending_amount_paise INTEGER NOT NULL DEFAULT 0,
      payment_status TEXT NOT NULL DEFAULT 'unpaid',
      notes TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS machine_rental_payments (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      machine_id TEXT NOT NULL,
      project_id TEXT,
      owner_name TEXT,
      payment_date INTEGER NOT NULL,
      amount_paise INTEGER NOT NULL DEFAULT 0,
      payment_mode TEXT,
      reference_number TEXT,
      notes TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS machine_repair_entries (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      machine_id TEXT NOT NULL,
      project_id TEXT,
      repair_date INTEGER NOT NULL,
      repair_description TEXT,
      mechanic_name TEXT,
      parts_cost_paise INTEGER NOT NULL DEFAULT 0,
      labor_cost_paise INTEGER NOT NULL DEFAULT 0,
      total_cost_paise INTEGER NOT NULL DEFAULT 0,
      paid_amount_paise INTEGER NOT NULL DEFAULT 0,
      pending_amount_paise INTEGER NOT NULL DEFAULT 0,
      notes TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS project_estimates (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      project_id TEXT NOT NULL,
      estimate_number TEXT,
      estimate_date INTEGER NOT NULL,
      title TEXT,
      total_estimated_material_cost_paise INTEGER NOT NULL DEFAULT 0,
      total_estimated_labor_cost_paise INTEGER NOT NULL DEFAULT 0,
      total_estimated_machinery_cost_paise INTEGER NOT NULL DEFAULT 0,
      total_estimated_other_cost_paise INTEGER NOT NULL DEFAULT 0,
      total_estimated_cost_paise INTEGER NOT NULL DEFAULT 0,
      estimated_profit_paise INTEGER NOT NULL DEFAULT 0,
      notes TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS project_estimate_items (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      estimate_id TEXT NOT NULL,
      item_name TEXT NOT NULL,
      description TEXT,
      unit TEXT,
      quantity_decimal TEXT NOT NULL DEFAULT '0',
      rate_paise INTEGER NOT NULL DEFAULT 0,
      amount_paise INTEGER NOT NULL DEFAULT 0
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS project_bills (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      project_id TEXT NOT NULL,
      bill_number TEXT NOT NULL,
      bill_date INTEGER NOT NULL,
      bill_type TEXT NOT NULL,
      gross_bill_amount_paise INTEGER NOT NULL DEFAULT 0,
      gst_rate_basis_points INTEGER NOT NULL DEFAULT 0,
      gst_amount_paise INTEGER NOT NULL DEFAULT 0,
      total_bill_amount_paise INTEGER NOT NULL DEFAULT 0,
      tds_amount_paise INTEGER NOT NULL DEFAULT 0,
      retention_amount_paise INTEGER NOT NULL DEFAULT 0,
      other_deduction_amount_paise INTEGER NOT NULL DEFAULT 0,
      net_receivable_amount_paise INTEGER NOT NULL DEFAULT 0,
      received_amount_paise INTEGER NOT NULL DEFAULT 0,
      pending_amount_paise INTEGER NOT NULL DEFAULT 0,
      status TEXT NOT NULL DEFAULT 'draft',
      notes TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS project_bill_receipts (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      project_id TEXT NOT NULL,
      bill_id TEXT NOT NULL,
      receipt_date INTEGER NOT NULL,
      amount_paise INTEGER NOT NULL DEFAULT 0,
      payment_mode TEXT,
      reference_number TEXT,
      notes TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS gst_entries (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      project_id TEXT,
      source_type TEXT NOT NULL,
      source_id TEXT NOT NULL,
      gst_type TEXT NOT NULL,
      gst_rate_basis_points INTEGER NOT NULL DEFAULT 0,
      taxable_amount_paise INTEGER NOT NULL DEFAULT 0,
      gst_amount_paise INTEGER NOT NULL DEFAULT 0,
      entry_date INTEGER NOT NULL,
      notes TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS project_expenses (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      project_id TEXT NOT NULL,
      expense_date INTEGER NOT NULL,
      expense_category TEXT NOT NULL,
      description TEXT,
      amount_paise INTEGER NOT NULL DEFAULT 0,
      paid_amount_paise INTEGER NOT NULL DEFAULT 0,
      pending_amount_paise INTEGER NOT NULL DEFAULT 0,
      payment_mode TEXT,
      notes TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS sync_queue (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      entity_type TEXT NOT NULL,
      entity_id TEXT NOT NULL,
      operation TEXT NOT NULL,
      payload_json TEXT NOT NULL,
      base_version INTEGER NOT NULL DEFAULT 0,
      new_version INTEGER NOT NULL DEFAULT 1,
      device_id TEXT NOT NULL,
      schema_version INTEGER NOT NULL,
      status TEXT NOT NULL DEFAULT 'pendingUpload',
      error_message TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS sync_deltas_applied (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      delta_id TEXT NOT NULL,
      entity_type TEXT NOT NULL,
      entity_id TEXT NOT NULL,
      operation TEXT NOT NULL,
      applied_at INTEGER NOT NULL,
      device_id TEXT,
      source_user_id TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS sync_conflicts (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      entity_type TEXT NOT NULL,
      entity_id TEXT NOT NULL,
      remote_delta_id TEXT,
      remote_operation TEXT,
      local_payload_json TEXT NOT NULL,
      remote_payload_json TEXT NOT NULL,
      local_version INTEGER NOT NULL,
      remote_version INTEGER NOT NULL,
      status TEXT NOT NULL DEFAULT 'open',
      resolved_by_user_id TEXT,
      resolved_at INTEGER,
      resolution TEXT
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS device_registry (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      device_id TEXT NOT NULL,
      firebase_uid TEXT,
      device_name TEXT,
      platform TEXT,
      last_sync_at INTEGER,
      status TEXT NOT NULL DEFAULT 'active'
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS staff_access_cache (
      id TEXT PRIMARY KEY,
      company_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      created_by_user_id TEXT,
      updated_by_user_id TEXT,
      is_deleted INTEGER NOT NULL DEFAULT 0,
      sync_status TEXT NOT NULL DEFAULT 'localOnly',
      version INTEGER NOT NULL DEFAULT 1,
      staff_id TEXT NOT NULL,
      firebase_uid TEXT,
      role_id TEXT,
      permission_json TEXT NOT NULL DEFAULT '{}',
      assigned_project_ids_json TEXT NOT NULL DEFAULT '[]',
      status TEXT NOT NULL DEFAULT 'active',
      cached_at INTEGER NOT NULL
    );
    '''
  ];

  static const List<String> createIndexes = <String>[
    'CREATE INDEX IF NOT EXISTS idx_tenders_company_status ON tenders(company_id, status);',
    'CREATE INDEX IF NOT EXISTS idx_projects_company_status ON projects(company_id, project_status);',
    'CREATE INDEX IF NOT EXISTS idx_material_purchases_project ON material_purchases(company_id, project_id);',
    'CREATE INDEX IF NOT EXISTS idx_labor_work_project ON labor_work_entries(company_id, project_id);',
    'CREATE INDEX IF NOT EXISTS idx_machine_usage_project ON machine_usage_entries(company_id, project_id);',
    'CREATE INDEX IF NOT EXISTS idx_fuel_project ON fuel_entries(company_id, project_id);',
    'CREATE INDEX IF NOT EXISTS idx_project_bills_project ON project_bills(company_id, project_id);',
    'CREATE INDEX IF NOT EXISTS idx_sync_queue_status ON sync_queue(company_id, status);',
    'CREATE INDEX IF NOT EXISTS idx_sync_queue_entity ON sync_queue(company_id, entity_type, entity_id);',
    'CREATE INDEX IF NOT EXISTS idx_sync_applied_delta ON sync_deltas_applied(company_id, delta_id);',
    'CREATE INDEX IF NOT EXISTS idx_staff_access_cache_staff ON staff_access_cache(company_id, staff_id);',
  ];
}
